services:
  fend:
    image: public.ecr.aws/l2y6y8r3/frontend:latest

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - fend
      - bend
    ports:
      - 80:80

  bend:
    image: public.ecr.aws/l2y6y8r3/backend:latest
    expose:
      - "5000"
    environment:
      - MONGO_URI=mongodb://db:27017/expense_db
      - JWT_SECRET=e581372412881a8a196c46b1d9d13f45a42be030085c4ba2baad205a8bd822c3
    depends_on:
      - db
    volumes:
      - expense_uploads:/app/uploads

  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  expense_uploads: